### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by mathuin** [mathuin/pyment#77]
```
Creating test database for alias 'default'...
.......F.F.F.......12 jars were created in SIP 1 A and placed in Crate 2
12 jars were created in SIP 1 A and placed in Crate 2
.14 jars were moved from crate 1 to crate 2
14 jars were moved from crate 1 to crate 2
..Removing inactive jars
11 jars were removed
Removing inactive jars
11 jars were removed
...........E...........EEE...E...
======================================================================
ERROR: test_add (meadery.tests.BatchTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/meadery/tests.py", line 376, in test_add
    self.populate_object(fields, ingredients)
  File "/opt/app/meadery/tests.py", line 65, in populate_object
    self.selenium.find_element_by_link_text('Add another Ingredient Item').click()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 254, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 662, in find_element
    {'using': by, 'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 173, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 166, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: {"errorMessage":"Unable to find element with link text 'Add another Ingredient Item'","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"115","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:38495","User-Agent":"Python-urllib/2.7"},"httpVersion":"1.1","method":"POST","post":"{\"using\": \"link text\", \"sessionId\": \"82561ea0-c1de-11e4-9f3b-376ac6aedaf7\", \"value\": \"Add another Ingredient Item\"}","url":"/element","urlParsed":{"anchor":"","query":"","file":"element","directory":"/","path":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/element","queryKey":{},"chunks":["element"]},"urlOriginal":"/session/82561ea0-c1de-11e4-9f3b-376ac6aedaf7/element"}}
Screenshot: available via screen


======================================================================
ERROR: test_add (meadery.tests.RecipeTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/meadery/tests.py", line 206, in test_add
    self.populate_object(fields, ingredients)
  File "/opt/app/meadery/tests.py", line 65, in populate_object
    self.selenium.find_element_by_link_text('Add another Ingredient Item').click()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 254, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 662, in find_element
    {'using': by, 'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 173, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 166, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: {"errorMessage":"Unable to find element with link text 'Add another Ingredient Item'","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"115","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:47682","User-Agent":"Python-urllib/2.7"},"httpVersion":"1.1","method":"POST","post":"{\"using\": \"link text\", \"sessionId\": \"d3dc2d00-c1de-11e4-b0cc-0307f49481b8\", \"value\": \"Add another Ingredient Item\"}","url":"/element","urlParsed":{"anchor":"","query":"","file":"element","directory":"/","path":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/element","queryKey":{},"chunks":["element"]},"urlOriginal":"/session/d3dc2d00-c1de-11e4-b0cc-0307f49481b8/element"}}
Screenshot: available via screen


======================================================================
ERROR: test_appellation (meadery.tests.RecipeTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/meadery/tests.py", line 305, in test_appellation
    self.populate_object(fields, ingredients)
  File "/opt/app/meadery/tests.py", line 65, in populate_object
    self.selenium.find_element_by_link_text('Add another Ingredient Item').click()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 254, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 662, in find_element
    {'using': by, 'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 173, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 166, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: {"errorMessage":"Unable to find element with link text 'Add another Ingredient Item'","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"115","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:47682","User-Agent":"Python-urllib/2.7"},"httpVersion":"1.1","method":"POST","post":"{\"using\": \"link text\", \"sessionId\": \"d3dc2d00-c1de-11e4-b0cc-0307f49481b8\", \"value\": \"Add another Ingredient Item\"}","url":"/element","urlParsed":{"anchor":"","query":"","file":"element","directory":"/","path":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/element","queryKey":{},"chunks":["element"]},"urlOriginal":"/session/d3dc2d00-c1de-11e4-b0cc-0307f49481b8/element"}}
Screenshot: available via screen


======================================================================
ERROR: test_category (meadery.tests.RecipeTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/meadery/tests.py", line 282, in test_category
    self.populate_object(fields, ingredients)
  File "/opt/app/meadery/tests.py", line 65, in populate_object
    self.selenium.find_element_by_link_text('Add another Ingredient Item').click()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 254, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 662, in find_element
    {'using': by, 'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 173, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 166, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: {"errorMessage":"Unable to find element with link text 'Add another Ingredient Item'","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"115","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:47682","User-Agent":"Python-urllib/2.7"},"httpVersion":"1.1","method":"POST","post":"{\"using\": \"link text\", \"sessionId\": \"d3dc2d00-c1de-11e4-b0cc-0307f49481b8\", \"value\": \"Add another Ingredient Item\"}","url":"/element","urlParsed":{"anchor":"","query":"","file":"element","directory":"/","path":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/element","queryKey":{},"chunks":["element"]},"urlOriginal":"/session/d3dc2d00-c1de-11e4-b0cc-0307f49481b8/element"}}
Screenshot: available via screen


======================================================================
ERROR: test_natural (meadery.tests.RecipeTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/meadery/tests.py", line 328, in test_natural
    self.populate_object(fields, ingredients)
  File "/opt/app/meadery/tests.py", line 65, in populate_object
    self.selenium.find_element_by_link_text('Add another Ingredient Item').click()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 254, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 662, in find_element
    {'using': by, 'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 173, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 166, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: {"errorMessage":"Unable to find element with link text 'Add another Ingredient Item'","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"115","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:47682","User-Agent":"Python-urllib/2.7"},"httpVersion":"1.1","method":"POST","post":"{\"using\": \"link text\", \"sessionId\": \"d3dc2d00-c1de-11e4-b0cc-0307f49481b8\", \"value\": \"Add another Ingredient Item\"}","url":"/element","urlParsed":{"anchor":"","query":"","file":"element","directory":"/","path":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/element","queryKey":{},"chunks":["element"]},"urlOriginal":"/session/d3dc2d00-c1de-11e4-b0cc-0307f49481b8/element"}}
Screenshot: available via screen


======================================================================
FAIL: test_cancel_picklist (checkout.tests.OrderTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/checkout/tests.py", line 90, in test_cancel_picklist
    self.assertEqual(sip1a.jar_set.filter(is_active=True).count(), 2)
AssertionError: 14 != 2

======================================================================
FAIL: test_create_picklist (checkout.tests.OrderTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/checkout/tests.py", line 48, in test_create_picklist
    self.assertEqual(sip1a.jar_set.filter(is_active=True).count(), 2)
AssertionError: 14 != 2

======================================================================
FAIL: test_process_picklist (checkout.tests.OrderTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/checkout/tests.py", line 69, in test_process_picklist
    self.assertEqual(sip1a.jar_set.filter(is_active=True).count(), 2)
AssertionError: 14 != 2

----------------------------------------------------------------------
Ran 55 tests in 250.964s

FAILED (failures=3, errors=5)
Destroying test database for alias 'default'...
```

Looks like two things to worry about -- the selenium stuff and the other stuff.

**Comment by mathuin** [comment]
These have since been fixed.  Yay!
